/**
 * Bundled offline fallback — keep in sync with
 * the official marketplace catalog.json (default GitHub raw URL in types.ts).
 */
import type { MarketplaceCatalog } from "./types.js";
import { emptyCatalog, MARKETPLACE_SCHEMA_VERSION } from "./types.js";

export const BUNDLED_MARKETPLACE_CATALOG: MarketplaceCatalog = emptyCatalog({
  schemaVersion: MARKETPLACE_SCHEMA_VERSION,
  updatedAt: "2026-08-07",
  name: "RoamSocket Official Marketplace",
  description:
    "Bundled fallback of the official catalog. Prefer live fetch from the default GitHub marketplace repo.",
  connectors: [
    { id: "cashapp", name: "Cash App", description: "Send and request money with Cash App.", available: true, category: "finance" },
    { id: "figma", name: "Figma", description: "Browse design files and frames from Figma.", available: true, category: "design" },
    { id: "gmail", name: "Gmail", description: "Search and summarize email from Gmail.", available: true, category: "productivity" },
    { id: "godaddy", name: "GoDaddy", description: "Domain and DNS management via GoDaddy.", available: true, category: "web" },
    { id: "gcal", name: "Google Calendar", description: "Upcoming events and scheduling context.", available: true, category: "productivity" },
    { id: "gdrive", name: "Google Drive", description: "Find and summarize Drive documents.", available: true, category: "productivity" },
    { id: "granola", name: "Granola", description: "Meeting notes from Granola.", available: false, category: "productivity" },
    { id: "github", name: "GitHub", description: "Issues, PRs, and repository context.", available: true, category: "engineering" },
  ],
  skills: [
    { id: "apa-formatting", name: "apa-formatting", description: "APA citations and paper structure", category: "documentation", author: "RoamSocket", source: "official", instructions: "# APA Formatting\n\nHelp the user write papers following APA 7th edition: title page, running head, in-text citations, and reference lists.\n\n## Invocation\n- \"format this in APA\"\n- \"APA citations for …\"\n" },
    { id: "canvas-design", name: "canvas-design", description: "Canvas / visual layout guidance", category: "design", author: "RoamSocket", source: "official", instructions: "# Canvas Design\n\nGuide layout, hierarchy, and visual composition for slides, posters, and canvas tools.\n\n## Invocation\n- \"design a canvas for …\"\n- \"improve this layout\"\n" },
    { id: "doc-coauthoring", name: "doc-coauthoring", description: "Collaborative document drafting", category: "documentation", author: "RoamSocket", source: "official", instructions: "# Doc Coauthoring\n\nDraft and revise long-form docs with clear sections, comments, and change proposals.\n\n## Invocation\n- \"coauthor this draft\"\n- \"revise section 2\"\n" },
    { id: "frontend-design-css", name: "frontend-design-css", description: "Premium HTML Landing Page Generator", category: "frontend", author: "RoamSocket", source: "official", featured: true, instructions: "# Landing — Premium HTML Landing Page Generator\n\nGenerate a polished, self-contained `.html` landing page from a text prompt or brief. The output is ONE HTML file: all CSS inline in `<style>`, all JS inline in `<script>`, only external dependencies being Google Fonts + GSAP via CDN. The page is visually distinctive, animated, and production-quality.\n\n## Invocation Triggers\n- \"create a landing page\"\n- \"build a landing page\"\n- \"make a landing page for X\"\n- \"I need a web page for Y\"\n" },
    { id: "internal-comms", name: "internal-comms", description: "Internal status and announcements", category: "other", author: "RoamSocket", source: "official", instructions: "# Internal Comms\n\nWrite crisp status updates, all-hands notes, and team announcements.\n\n## Invocation\n- \"write a status update\"\n- \"announce …\"\n" },
    { id: "mcp-builder", name: "mcp-builder", description: "Guide for creating high-quality MCP servers", category: "devops", author: "RoamSocket", source: "official", featured: true, instructions: "# MCP Builder\n\nGuide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external tools and data sources.\n\n## Goals\n- Clear tool schemas and descriptions\n- Safe auth and error handling\n- Idiomatic TypeScript / Python server layouts\n\n## Invocation\n- \"build an MCP server\"\n- \"add tools for …\"\n- \"/mcp-builder\"\n" },
    { id: "morning", name: "morning", description: "Daily brief and prioritization", category: "other", author: "RoamSocket", source: "official", instructions: "# Morning\n\nProduce a focused daily brief: top 3 priorities, calendar risks, and one stretch goal.\n\n## Invocation\n- \"morning brief\"\n- \"what should I focus on today\"\n" },
    { id: "skill-creator", name: "skill-creator", description: "Author new agent skills", category: "other", author: "RoamSocket", source: "official", featured: true, instructions: "# Skill Creator\n\nHelp the user design SKILL.md files: name, description, triggers, and instructions.\n\n## Invocation\n- \"create a skill\"\n- \"skill for …\"\n" },
    { id: "theme-factory", name: "theme-factory", description: "UI theme tokens and palettes", category: "design", author: "RoamSocket", source: "official", instructions: "# Theme Factory\n\nGenerate cohesive color tokens, typography scales, and CSS variables for product UI.\n\n## Invocation\n- \"make a theme\"\n- \"palette for …\"\n" },
  ],
  plugins: [
    { id: "marketing-kit", name: "Marketing kit", description: "Landing pages, campaigns, and brand voice helpers.", category: "marketing", skillIds: ["frontend-design-css", "theme-factory"], featured: true },
    { id: "productivity-kit", name: "Productivity kit", description: "Daily briefs, internal comms, and doc coauthoring.", category: "productivity", skillIds: ["morning", "internal-comms", "doc-coauthoring"], featured: true },
    { id: "engineering-kit", name: "Engineering kit", description: "MCP builders and developer-oriented skills.", category: "engineering", skillIds: ["mcp-builder", "skill-creator"], featured: true },
    { id: "design-kit", name: "Design kit", description: "Canvas layout and theme tokens.", category: "design", skillIds: ["canvas-design", "theme-factory"], featured: false },
  ],
  pluginCategories: [
    { id: "marketing", label: "Marketing" },
    { id: "productivity", label: "Productivity" },
    { id: "engineering", label: "Engineering" },
    { id: "design", label: "Design" },
  ],
  metalModels: [
    {
      hubID: "lmstudio-community/LFM2.5-1.2B-Instruct-MLX-4bit",
      displayName: "LFM2.5 1.2B",
      approxSize: "~0.7 GB",
      blurb: "Liquid AI LFM2.5 — strong everyday chat and a great on-device starting point.",
      tags: ["recommended", "best", "new"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/Qwen3-0.6B-MLX-4bit",
      displayName: "Qwen 3 0.6B",
      approxSize: "~0.4 GB",
      blurb: "Tiny Qwen 3 for low storage and fast replies.",
      tags: ["recommended", "new"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/Qwen3-1.7B-MLX-4bit",
      displayName: "Qwen 3 1.7B",
      approxSize: "~1.0 GB",
      blurb: "Balanced Qwen 3 size for everyday on-device chat.",
      tags: ["recommended", "new"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/Qwen3-4B-Instruct-2507-MLX-4bit",
      displayName: "Qwen 3 4B Instruct",
      approxSize: "~2.3 GB",
      blurb: "Stronger Qwen 3 instruct for higher quality when RAM allows.",
      tags: ["recommended", "new"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/Qwen3-4B-Thinking-2507-MLX-4bit",
      displayName: "Qwen 3 4B Thinking",
      approxSize: "~2.3 GB",
      blurb: "Qwen 3 thinking variant for chain-of-thought style replies.",
      tags: ["recommended", "thinking", "new"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/Qwen2.5-0.5B-Instruct-MLX-4bit",
      displayName: "Qwen 2.5 0.5B",
      approxSize: "~0.3 GB",
      blurb: "Ultra-small Qwen 2.5 instruct for smoke tests and tight storage.",
      tags: ["recommended"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/Qwen2.5-1.5B-Instruct-MLX-4bit",
      displayName: "Qwen 2.5 1.5B",
      approxSize: "~0.9 GB",
      blurb: "Compact multilingual instruct model with solid multi-turn chat.",
      tags: ["recommended"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/Qwen2.5-3B-Instruct-MLX-4bit",
      displayName: "Qwen 2.5 3B",
      approxSize: "~1.8 GB",
      blurb: "Larger Qwen 2.5 instruct for higher-quality chat when RAM allows.",
      tags: ["recommended"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/Qwen2.5-Coder-1.5B-Instruct-MLX-4bit",
      displayName: "Qwen 2.5 Coder 1.5B",
      approxSize: "~0.9 GB",
      blurb: "Small code-focused instruct model for on-device coding chat.",
      tags: ["recommended"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/Phi-4-mini-reasoning-MLX-4bit",
      displayName: "Phi 4 Mini Reasoning",
      approxSize: "~2.2 GB",
      blurb: "Microsoft Phi 4 mini for compact reasoning and chat.",
      tags: ["recommended", "thinking", "new"],
      platforms: ["ios", "desktop"],
    },
    {
      hubID: "lmstudio-community/gemma-3-270m-it-qat-MLX-4bit",
      displayName: "Gemma 3 270M QAT",
      approxSize: "~0.2 GB",
      blurb: "Tiny Gemma for smoke tests and ultra-low storage.",
      tags: ["recommended"],
      platforms: ["ios", "desktop"],
    },
  ],
});
