import type { ForgeConfig } from '@electron-forge/shared-types';
import { MakerSquirrel } from '@electron-forge/maker-squirrel';
import { MakerZIP } from '@electron-forge/maker-zip';
import { MakerDeb } from '@electron-forge/maker-deb';
import { MakerRpm } from '@electron-forge/maker-rpm';
import { MakerDMG } from '@electron-forge/maker-dmg';
import { VitePlugin } from '@electron-forge/plugin-vite';

const config: ForgeConfig = {
  packagerConfig: {
    asar: true,
    name: 'RoamSocket',
    executableName: 'roamsocket',
    appBundleId: 'app.roamsocket.desktop',
    // Icon sources generated by scripts/icons/build_icons.py. Forge picks
    // `icon.icns` on macOS, `icon.ico` on Windows, and `icon.png` everywhere
    // else (Linux tray / window list / packaged app icon).
    icon: 'build/icon',
    // Ship the full icon set (tray templates, light/dark variants) so the
    // running app can read them at runtime. The Forge `icon` above embeds
    // just the multi-res master into the bundle; the rest need to live next
    // to the packaged binary. On `electron-forge package`, `build/` ends up
    // at `<app>/Contents/Resources/build/` on macOS and equivalent on
    // Windows / Linux — see `iconDir()` in src/electron/main.ts.
    extraResource: 'build',
  },
  rebuildConfig: {},
  makers: [
    new MakerZIP({}, ['darwin', 'linux', 'win32']),
    new MakerSquirrel({ name: 'roamsocket' }, ['win32']),
    new MakerDMG({}, ['darwin']),
    new MakerDeb({}),
    new MakerRpm({}),
  ],
  plugins: [
    new VitePlugin({
      build: [
        {
          entry: 'src/electron/main.ts',
          config: 'vite.main.config.ts',
          target: 'main',
        },
        {
          entry: 'src/electron/preload.ts',
          config: 'vite.preload.config.ts',
          target: 'preload',
        },
      ],
      renderer: [
        {
          name: 'main_window',
          config: 'vite.renderer.config.ts',
        },
      ],
    }),
  ],
};

export default config;
